# Generated by Django 2.0.7 on 2018-08-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='weather',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
