# Generated by Django 2.0.7 on 2018-08-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RestAPI', '0002_auto_20180826_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='temperature',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.Weather'),
        ),
        migrations.AddField(
            model_name='location',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.Weather'),
        ),
    ]
