# Generated by Django 2.0.7 on 2018-08-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_auto_20180826_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='RestAPI.Weather'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='RestAPI.Weather'),
        ),
    ]
