# Generated by Django 2.0.7 on 2018-08-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0004_auto_20180826_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='weather',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='RestAPI.Weather'),
        ),
    ]
